### PR TITLE
Pull Request For Issue #307

### PR DESCRIPTION
**Pull request by vibhuti019**
Issue #307 
Working for aligning icons similar to google photos.
Added React Native Video Player.
Removed expo-av

### CODE REVIEW

**Comment by vibhuti019** [comment]
I am still working to improve the feature.

**Comment by vibhuti019** [comment]
TODO: 
The PinchGesture and TapGesture parent elements should be removed as it zooms the video with the pinch and tap gesture.
React-native-video-player has icons at different places
We need to use react-native-video library (without controls) and then add buttons according to our requirements

**Comment by ghorbani-m** [comment]
Thanks, @vibhuti019 , Could you please make PR on the develop branch? now you have made PR on the master branch

**Comment by vibhuti019** [comment]
@ghorbani-m done sir

**Comment by vibhuti019** [comment]
I think we need to update we can't use react-native-video-player, we need to use react-native-video and above that another view

**Comment by ghorbani-m** [comment]
Incompleted

**Pull request closed without merging**
